apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "scst.fullname" . }}-processor
  labels:
    app.kubernetes.io/name: {{ include "scst.name" . }}-processor
    helm.sh/chart: {{ include "scst.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.processor.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "scst.name" . }}-processor
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "scst.name" . }}-processor
        app.kubernetes.io/instance: {{ .Release.Name }}
        app: {{ include "scst.name" . }}-processor
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8080"
    spec:
      serviceAccount: {{ include "scst.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.processor.image.repository }}:{{ .Values.processor.image.tag }}"
          imagePullPolicy: {{ .Values.processor.image.pullPolicy }}
          env:
            - name: SPRING_CLOUD_KUBERNETES_CONFIG_NAME
              value: "{{ include "scst.fullname" . }}-processor"
            - name: SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS
              value: "{{ .Release.Name }}-kafka:9092"
            - name: SPRING_PROFILES_ACTIVE
              value: kubernetes
            - name: SPRING_RABBITMQ_HOST
              value: "{{ .Release.Name }}-rabbitmq-ha"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          # livenessProbe:
            # httpGet:
              # path: /actuator/health
              # port: http
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
          reprocessors:
            {{- toYaml .Values.reprocessors | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
