# Default values for scst.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

sink:
  image:
    repository: paulczar/scst-sink
    tag: 0.0.1-SNAPSHOT
    pullPolicy: Always
  replicaCount: 1
  config: |-
    # config settings loaded from values

source:
  image:
    repository: paulczar/scst-source
    tag: 0.0.1-SNAPSHOT
    pullPolicy: Always
  replicaCount: 1
  config: |-
    # config settings loaded from values
processor:
  image:
    repository: paulczar/scst-processor
    tag: 0.0.1-SNAPSHOT
    pullPolicy: Always
  replicaCount: 1
  config: |-
    # config settings loaded from values

prometheus:
  enabled: true


nameOverride: ""
fullnameOverride: ""

rbac:
  enabled: true

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
  paths:
    - path: /source
      service: source
    - path: /processor
      service: processor
    - path: /sink
      service: sink
  hosts:
    - cofee.demo.paulczar.wtf
  tls: []
#  - secretName: coffee-tls
#    hosts:
#      - cofee.demo.paulczar.wtf

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

cp-helm-charts:
  enabled: true
  persistence:
    enabled: false


kafka:
  enabled: true
  persistence:
    enabled: false
#  advertisedListeners: PLAINTEXT://coffee-kafka:9092
  zookeeper:
    persistence:
      enabled: false

zookeeper:
  persistence:
    enabled: false

rabbitmq:
  enabled: true
  username: user
  password: coffee

rabbitmq-ha:
  replicaCount: 1
  enabled: true
  rabbitmqUsername: user
  rabbitmqPassword: coffee
  managementUsername: admin
  managementPassword: coffee

prometheus:
  enabled: false

grafana:
  enabled: false