apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: hello
  name: hello
spec:
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - env:
        - name: KUBERNETES_TRUST_CERTIFICATES
          value: "true"
        - name: SPRING_CLOUD_KUBERNETES_CONFIG_NAMESPACE
          valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        image: paulczar/spring-hello:0.0.1
        imagePullPolicy: Never
        name: hello
        ports:
          - name: http
            containerPort: 8080
          - name: actuator
            containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 500m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: actuator
          initialDelaySeconds: 60
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: actuator
