version: '3'
services:

  source:
    image: paulczar/scst-source:0.0.1-SNAPSHOT
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq

  processor:
    image: paulczar/scst-processor:0.0.1-SNAPSHOT
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS: kafka:9092

  sink:
    image: paulczar/scst-sink:0.0.1-SNAPSHOT
    environment:
      SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS: kafka:9092

  kafka:
    image: confluentinc/cp-kafka:5.0.0
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
    ports:
      - 9092:9092

  zookeeper:
    image: confluentinc/cp-zookeeper:5.0.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - 2181:2181


  rabbitmq:
    image: rabbitmq:management
    ports:
      - 5671:5671
      - 15671:15671
